### ISSUE TITLE
Sankey diagrams/transition plots as a ggplot2 extension 

### ISSUE THREAD

**Issue by timchurches** [ropensci/ozunconf17#6]
Port or re-implement static Sankey diagrams/Parallel Co-ordinate Plots (see https://cran.r-project.org/web/packages/alluvial/vignettes/alluvial.html ) and/or transition plots (see https://cran.r-project.org/web/packages/Gmisc/vignettes/transitionPlot.html ) to the ggplot2 environment as an extension geom.

See p37 onwards in this report for examples of transition plots in use: http://www.acornregistry.org/images/Acorn-Annual-Report-2016-v12.pdf

There are also the riverplot and sankey packages (see https://cran.r-project.org/web/packages/riverplot/riverplot.pdf and https://cran.r-project.org/web/packages/sankey/sankey.pdf), and gvisSankey in the googleVis package (see https://www.rdocumentation.org/packages/googleVis/versions/0.6.0/topics/gvisSankey). None of these work with the ggplot2 ecosystem.

**Comment by njtierney** [comment]
I do love sankey charts - I wonder if we need to consider a data-preprocessing step here as well, to get things into the right format? @dicook any thoughts?

**Comment by timchurches** [comment]
Yes, for a Sankey extension to ggplot2, an important issue is how it fits into the whole tidy data/dplyr functional programming  paradigm, and whether it might be useful to add some helper functions to, say, the purrr package to make pipelined data preparation easier, as you suggest. The transitionPlot() in the Gmisc package requires the data to be transformed into a transition matrix, as a matrix object. Not difficult, but it feels out-of-step when doing everything else with ggplot2 and data frames/tibbles.

**Comment by njtierney** [comment]
By chance there has been some discussion on Twitter about Sankey charts: https://twitter.com/Md_Harris/status/915388811185721344 Might be of use!

**Comment by timchurches** [comment]
Ah, OK, I didn't know about ggalluvial, and or geom_parallel_sets in ggforce. Looks like Sankey diagrams in ggplot2 is a solved problem. But I'm now reminded how useful ggforce is. Maybe there are some other ggplot2 customisations or extensions that could be considered? More thinking...

**Comment by timchurches** [comment]
ggalluvial works quite well, although with some artefacts in the plotting of the transition streams:

<img width="1281" alt="screen shot 2017-10-22 at 17 32 58" src="https://user-images.githubusercontent.com/2859105/31858949-c643bb0e-b74f-11e7-9075-acafd679517a.png">

**Comment by timchurches** [comment]
I didn't have any success with the geom_parallel_sets() geom in the ggforce package, but perhaps that's because it seems to be set up for true Sankey diagrams, whereas what i wanted was actually an alluvial diagram, as above. Anyway, I'll submit an issue report for the artifactual flaws in the ggalluvial output, but it is good enough, and the package easy enough to use, to declare this a solved problem, I think.

**Comment by njtierney** [comment]
@timchurches it sounds like this is wrapped up, are you happy to close this?
