### ISSUE TITLE
extend naniar package for multiple types of missing value

### ISSUE THREAD

**Issue by rgayler** [ropensci/ozunconf17#8]
naniar currently only categorises variable values as missing or not-missing. The vignette, in discussing the shadow matrix mentions that it can be extended to deal with multiple types of missing (e.g. not applicable, not asked, not answered) but i can't see an evidence from the function documentation that this has been done.  (I am happy to be shown to be wrong on this @njtierney.)

In some domains, different types of missingness are common. Also, SAS software allows the programmer to use multiple, distinguishable types of missing - so being able to support this would facilitate data import from SAS.

I would be interested in extending naniar to handle multiple types of missing.

**Comment by njtierney** [comment]
Very happy to hear this is of interest!

This is indeed on the radar for a future release of naniar. However, just to address the comment for SAS / STATA - you can import these different kinds of missing values using the `haven` package. 

naniar should probably have some way of translating these to the shadow matrix, but at the moment the emphasis is going to be on R users, and facilitating their decisions to allocate different kinds of missing values.

The current discussion on this topic can be seen [here](https://github.com/njtierney/naniar/issues/50)

**Comment by njtierney** [comment]
I'm going to close this issue as it is better discussed on the naniar repo
